import { POSITION_CODES, type PositionCode, type TargetingRule } from "./types";

const ALL_TARGET_MODES = ["POSITION", "PERSON"] as const;
const SCHOOL_HEAD_UNIT_IDS = [
  "manar_girls",
  "rawdat_1",
  "rawdat_2",
  "rawdat_3",
  "rawdat_4",
] as const;
const LOCAL_SCHOOL_STAFF: readonly PositionCode[] = [
  "teacher",
  "administrative_staff",
  "deputy_principal",
  "trainee",
  "early_childhood_caregiver",
  "student_support",
  "students_mentor",
  "school_monitor",
  "activity_lead",
  "media_specialist",
];

// Rules identify positions and organizational relationships only. They contain
// no employee, email, UID, or legacy-recipient identity.
export const TARGETING_RULES: readonly TargetingRule[] = [
  {
    id: "local-staff-to-principal",
    senderPositions: LOCAL_SCHOOL_STAFF,
    targetPositions: ["principal"],
    scope: "same_unit",
    allowedTargetModes: ALL_TARGET_MODES,
  },
  {
    id: "school-principal-to-local-staff",
    senderPositions: ["principal"],
    targetPositions: LOCAL_SCHOOL_STAFF,
    scope: "same_unit",
    allowedTargetModes: ALL_TARGET_MODES,
  },
  {
    id: "school-principal-to-executive-assistant",
    senderPositions: ["principal"],
    excludedSourceOrgUnitIds: ["manar_boys_sayh", "manar_boys_faleh"],
    targetPositions: ["executive_assistant"],
    scope: "related_unit",
    relationship: "executive_unit",
    allowedTargetModes: ALL_TARGET_MODES,
  },
  {
    id: "school-principal-to-supervision-leadership",
    senderPositions: ["principal"],
    excludedSourceOrgUnitIds: ["manar_boys_sayh", "manar_boys_faleh"],
    targetPositions: ["administrative_supervisor", "educational_supervisor"],
    scope: "related_unit",
    relationship: "supervision_unit",
    allowedTargetModes: ALL_TARGET_MODES,
  },
  {
    id: "manar-boys-principal-to-supervision-head",
    senderPositions: ["principal"],
    sourceOrgUnitIds: ["manar_boys_sayh", "manar_boys_faleh"],
    targetPositions: ["supervision_head"],
    scope: "related_unit",
    relationship: "supervision_unit",
    allowedTargetModes: ALL_TARGET_MODES,
  },
  {
    id: "subject-supervisor-to-supervision-head",
    senderPositions: ["supervisor"],
    targetPositions: ["supervision_head"],
    scope: "same_unit",
    allowedTargetModes: ALL_TARGET_MODES,
  },
  {
    id: "supervision-head-to-ceo",
    senderPositions: ["supervision_head"],
    targetPositions: ["ceo"],
    scope: "related_unit",
    relationship: "executive_unit",
    allowedTargetModes: ALL_TARGET_MODES,
  },
  {
    id: "supervision-head-to-manar-boys-principals",
    senderPositions: ["supervision_head"],
    targetPositions: ["principal"],
    targetOrgUnitIds: ["manar_boys_sayh", "manar_boys_faleh"],
    scope: "global",
    allowedTargetModes: ALL_TARGET_MODES,
  },
  {
    id: "supervision-head-to-subject-supervisors",
    senderPositions: ["supervision_head"],
    targetPositions: ["supervisor"],
    scope: "same_unit",
    allowedTargetModes: ALL_TARGET_MODES,
  },
  {
    id: "administrative-supervisor-to-ceo",
    senderPositions: ["administrative_supervisor"],
    targetPositions: ["ceo"],
    scope: "related_unit",
    relationship: "executive_unit",
    allowedTargetModes: ALL_TARGET_MODES,
  },
  {
    id: "administrative-supervisor-to-school-heads",
    senderPositions: ["administrative_supervisor"],
    targetPositions: ["principal"],
    targetOrgUnitIds: SCHOOL_HEAD_UNIT_IDS,
    scope: "global",
    allowedTargetModes: ALL_TARGET_MODES,
  },
  {
    id: "educational-supervisor-to-ceo",
    senderPositions: ["educational_supervisor"],
    targetPositions: ["ceo"],
    scope: "related_unit",
    relationship: "executive_unit",
    allowedTargetModes: ALL_TARGET_MODES,
  },
  {
    id: "educational-supervisor-to-school-heads",
    senderPositions: ["educational_supervisor"],
    targetPositions: ["principal"],
    targetOrgUnitIds: SCHOOL_HEAD_UNIT_IDS,
    scope: "global",
    allowedTargetModes: ALL_TARGET_MODES,
  },
  {
    id: "executive-assistant-to-ceo",
    senderPositions: ["executive_assistant"],
    targetPositions: ["ceo"],
    scope: "same_unit",
    allowedTargetModes: ALL_TARGET_MODES,
  },
  {
    id: "executive-assistant-to-school-heads",
    senderPositions: ["executive_assistant"],
    targetPositions: ["principal"],
    targetOrgUnitIds: SCHOOL_HEAD_UNIT_IDS,
    scope: "global",
    allowedTargetModes: ALL_TARGET_MODES,
  },
  {
    id: "executive-functions-to-ceo",
    senderPositions: ["hr", "finance", "collector", "secretary"],
    targetPositions: ["ceo"],
    scope: "related_unit",
    relationship: "executive_unit",
    allowedTargetModes: ALL_TARGET_MODES,
  },
  {
    id: "platforms-to-ceo",
    senderPositions: ["platforms_specialist"],
    targetPositions: ["ceo"],
    scope: "global",
    allowedTargetModes: ALL_TARGET_MODES,
  },
  {
    id: "projects-to-ceo-and-maintenance",
    senderPositions: ["projects"],
    targetPositions: ["ceo", "maintenance"],
    scope: "global",
    allowedTargetModes: ALL_TARGET_MODES,
  },
  {
    id: "maintenance-to-projects",
    senderPositions: ["maintenance"],
    targetPositions: ["projects"],
    scope: "global",
    allowedTargetModes: ALL_TARGET_MODES,
  },
  {
    id: "media-manager-to-ceo-and-designer",
    senderPositions: ["media_manager"],
    targetPositions: ["ceo", "designer"],
    scope: "global",
    allowedTargetModes: ALL_TARGET_MODES,
  },
  {
    id: "designer-to-media-manager",
    senderPositions: ["designer"],
    targetPositions: ["media_manager"],
    scope: "global",
    allowedTargetModes: ALL_TARGET_MODES,
  },
  {
    id: "binaa-boys-to-ceo",
    senderPositions: ["center_manager"],
    sourceOrgUnitIds: ["bena_center_boys"],
    targetPositions: ["ceo"],
    scope: "related_unit",
    relationship: "executive_unit",
    allowedTargetModes: ALL_TARGET_MODES,
  },
  {
    id: "binaa-boys-to-paired-center",
    senderPositions: ["center_manager"],
    sourceOrgUnitIds: ["bena_center_boys"],
    targetPositions: ["center_manager"],
    scope: "related_unit",
    relationship: "paired_center_unit",
    allowedTargetModes: ALL_TARGET_MODES,
  },
  {
    id: "binaa-girls-to-paired-center",
    senderPositions: ["center_manager"],
    sourceOrgUnitIds: ["bena_center_girls"],
    targetPositions: ["center_manager"],
    scope: "related_unit",
    relationship: "paired_center_unit",
    allowedTargetModes: ALL_TARGET_MODES,
  },
  {
    id: "athar-center-to-ceo",
    senderPositions: ["athar_center_manager"],
    targetPositions: ["ceo"],
    scope: "related_unit",
    relationship: "executive_unit",
    allowedTargetModes: ALL_TARGET_MODES,
  },
  {
    id: "ceo-to-chairman",
    senderPositions: ["ceo"],
    targetPositions: ["chairman"],
    scope: "related_unit",
    relationship: "council_unit",
    allowedTargetModes: ALL_TARGET_MODES,
  },
  {
    id: "chairman-global",
    senderPositions: ["chairman"],
    targetPositions: POSITION_CODES,
    scope: "global",
    allowedTargetModes: ALL_TARGET_MODES,
  },
  {
    id: "ceo-global",
    senderPositions: ["ceo"],
    targetPositions: POSITION_CODES,
    scope: "global",
    allowedTargetModes: ALL_TARGET_MODES,
  },
];
